# Diferenças Finitas para Equações Hiperbólicas de Primeira Ordem


In [10]:
import numpy as np
u = np.zeros(6)
u[0]=1.
n = 5
u_ant = np.ones(n+1)
print (u_ant)

for i in range(1,100,1):
    for j in range(1,n,1):
        u[0] = 0.
        u[j] = 0.5*u_ant[j]+0.25*(u_ant[j+1]+u_ant[j-1])
        
    u[n] = 0.5*u_ant[n-1]+0.25*(u_ant[n-2]-0.4*u_ant[n-1]+u_ant[n-2])
    u_ant = u
    print (u)
    

[ 1.  1.  1.  1.  1.  1.]
[ 0.   1.   1.   1.   1.   0.9]
[ 0.          0.75        0.9375      0.984375    0.97109375  0.880625  ]
[ 0.          0.609375    0.8671875   0.95175781  0.94364258  0.85333594]
[ 0.          0.52148438  0.8019043   0.91226563  0.91322168  0.82142148]
[ 0.          0.46121826  0.74432312  0.87051901  0.87959596  0.78709789]
[ 0.          0.41668991  0.69396379  0.82864944  0.84373482  0.75181865]
[ 0.          0.3818359   0.64960323  0.78765923  0.80673688  0.71652437]
[ 0.          0.35331876  0.61004611  0.74802537  0.76950587  0.68181503]
[ 0.          0.32917091  0.57432213  0.70996968  0.73269912  0.64806449]
[ 0.          0.30816599  0.54169498  0.67358337  0.69676152  0.61549629]
[ 0.          0.28950674  0.51162002  0.63888707  0.6619766   0.58423417]
[ 0.          0.27265837  0.48369637  0.60586178  0.62851229  0.5543358 ]
[ 0.          0.25725328  0.45762695  0.5744657   0.59645652  0.52581546]
[ 0.          0.24303338  0.43318824  0.54464404  0.56